# Generated by Django 5.2.17 on 2026-08-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATING", "Validating"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=24,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("failed_files", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration", models.FloatField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_files",
                        to="analysis.batch",
                    ),
                ),
            ],
            options={
                "ordering": ["filename"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emotional_tone",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "emotional_intensity",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("background_noise_present", models.BooleanField(default=False)),
                (
                    "background_noise_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "background_noise_severity",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "audio_quality",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("speaker_overlap_present", models.BooleanField(default=False)),
                ("long_silence_present", models.BooleanField(default=False)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "audio_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="analysis.audiofile",
                    ),
                ),
            ],
        ),
    ]
